---
title: "Raw Data"
execute:
  freeze: auto
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(kableExtra)
```

Here's the raw data, refreshed every week or so.  
Get the CSV file for import in arbitrary software, and the RDS file if you happen to use R. 
Note that as of now ATP is not available as a CSV file since the datasets contains a per-episode nested list-column of all the HTTP links from the shownotes and CSV doesn't like that. 


```{r}
files <- fs::dir_ls(here::here("data"), regexp = "\\.csv$|\\.rds$")

fs::file_info(files) |>
  select(path, size, change_time) |>
  mutate(
    path = fs::path_file(path),
    shownet = case_when(
      grepl("atp", path) ~ "ATP",
      grepl("incomp", path) ~ "The Incomparable",
      grepl("relay", path) ~ "Relay FM",
      TRUE ~ "?"
    ),
    path = glue::glue("<a href='/data/{path}'>{path}</a>")
  ) |>
  select(shownet, change_time, size, path) |>
  kable(
    col.names = c("Network/Show", "Last Updated", "Size", "Download"),
    escape = FALSE, format = "html"
  ) |>
  kable_styling(full_width = TRUE) |>
  collapse_rows(1)
```
