---
title: "The Incomparable: Network Wide"
date: "`r format(Sys.time(), '%F %R', tz = 'UTC', usetz = T)`"
author: "Lukas — @jemus42"
output: 
  html_document:
    fig_height: 8
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
#### Global options ####
options(max.print = "75")
opts_chunk$set(echo    = FALSE,
	             cache   = FALSE,
               prompt  = FALSE,
               tidy    = TRUE,
               comment = NA,
               message = FALSE,
               warning = FALSE,
               fig.retina = 2,
               fig.path = "assets/incomparable_main/")
opts_knit$set(width = 75)

#### Data prep ####
source("setup.R")

incomparable_wide <- readRDS("data/incomparable_master_wide.rds")
incomparable      <- readRDS("data/incomparable_master.rds")
```

## 2017 Hosts and Guests

```{r 2017_panelists_network, fig.height=14}
incomparable %>% 
  filter(year == 2017) %>%
  group_by(person, role) %>%
  tally() %>%
  spread(role, n) %>% 
  replace_na(list(guest = 0, host = 0)) %>%
  mutate(total = guest + host) %>%
  arrange(desc(total)) %>%
  datatable(style = "bootstrap", colnames = c("Person", "Guest", "Host", "Total Appearances"))

incomparable %>% 
  filter(year == 2017) %>%
  group_by(person, role) %>%
  tally() %>%
  {
    ggplot(data = ., aes(x = reorder(person, n), y = n, fill = role)) +
      geom_col(color = "black", alpha = .6) +
      coord_flip() +
      scale_y_continuous(breaks = seq(0, 100, 5), minor_breaks = seq(0, 100, 1)) +
      scale_fill_brewer(palette = "Set1") +
      labs(title = "The Incomparable — 2017", subtitle = "Panelists by # of Appearances",
           x = "Panelist", y = "# of Appearances", fill = "Role") +
      theme(legend.position = "bottom")
  }
```
