---
title: "The Incomparable 10th Anniversary Special"
date: "`r format(Sys.time(), '%F %R', tz = 'UTC', usetz = T)`"
author: "Lukas — @jemus42"
output: 
  html_document:
    fig_height: 8
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
source("00_setup.R")
library(epoxy)

#### Global options ####
knitr::opts_chunk$set(
  fig.path = "assets/plots/incomparable_tenth/"
)

incomparable_wide <- readRDS("data/incomparable_master_wide.rds") %>%
  filter(podcast == "The Incomparable") %>%
  filter(!str_detect(number, "[a-z]$"))

incomparable <- readRDS("data/incomparable_master.rds") %>%
  filter(podcast == "The Incomparable") %>%
  filter(!str_detect(number, "[a-z]$"))
```

```{glue tenth-summary, .transformer = epoxy_style_bold()}
Since its first episode on {format(min(as.Date(incomparable_wide$date)), "%B %d, %Y")}, The Incomparable has accumulated {round(sum(incomparable_wide$duration)/60)} hours of content (roughly {round(sum(incomparable_wide$duration)/60/24)} days) across {nrow(incomparable_wide)} episodes.
```



The latest episode in the current dataset:

```{r tenth-latest-data}
incomparable_wide %>%
  head(1) %>%
  select(number, date, title, host, guest) %>%
  mutate(date = as.Date(date)) %>%
  kable()
```


## All the panelists!

```{r tenth-panelists}
incomparable %>%
  count(person, role) %>%
  pivot_wider(names_from = role, values_from = n, values_fill = 0) %>%
  mutate(
    person = factor(person),
    total = guest + host,
    total_perc = total / nrow(incomparable_wide),
    rank = rank(-total, ties.method = "min")
  ) %>%
  arrange(desc(total)) %>%
  select(rank, person, host, guest, total, total_perc) %>%
  datatable(
    style = "bootstrap",
    filter = "top",
    colnames = c("Rank", "Person", "Host", "Guest", "Total", "Total %"), 
    rownames = FALSE,
    options = list(
       pageLength = 25,
       lengthMenu = c(10, 25, 50, 100)
    )
  ) %>%
  formatPercentage(columns = 6, digits = 1)
```

### By Segment

The segments the dataset knows about, with episode count:

```{r tenth-segments}
incomparable_wide %>%
  count(segment, sort = TRUE) %>%
  replace_na(replace = list(segment = "(General)")) %>%
  kable()
```

Ranks within segment:

```{r tenth-panelists-segments}
incomparable %>%
  count(segment, person, role) %>%
  filter(!is.na(segment)) %>%
  pivot_wider(names_from = role, values_from = n, values_fill = 0) %>%
  mutate(
    segment = factor(segment), person = factor(person),
    total = guest + host,
    total_perc = total / nrow(incomparable_wide),
    rank = rank(-total, ties.method = "min")
  ) %>%
  group_by(segment) %>%
  mutate(
    rank = rank(-total, ties.method = "min")
  ) %>%
  arrange(segment, desc(total)) %>%
  select(segment, rank, person, host, guest, total, total_perc) %>%
  datatable(
    style = "bootstrap",
    colnames = c("Segment", "Rank", "Person", "Host", "Guest", "Total", "Total %"), 
    rownames = FALSE,
    filter = "top",
    extensions = "RowGroup",
    options = list(
       rowGroup = list(dataSrc = 0),
       pageLength = 50,
       lengthMenu = c(10, 25, 50, 75, 120)
    )
  ) %>%
  formatPercentage(columns = 7, digits = 1)
```

### By Duration of Appearance

```{r tenth-panelists-duration}
incomparable %>%
  group_by(person) %>%
  summarize(mins = sum(duration)) %>%
  mutate(
    mins = round(mins, 1),
    hours = round(mins/60, 1), 
    days = round(hours/24, 1),
    person = factor(person),
    runtime_perc = mins / sum(incomparable_wide$duration),
    rank = rank(-mins, ties.method = "min")
  ) %>%
  arrange(rank) %>%
  select(rank, person, runtime_perc, mins, hours, days) %>%
  datatable(
    style = "bootstrap",
    filter = "top",
    colnames = c("Rank", "Person", "% of All", "Minutes", "Hours", "Days"), 
    rownames = FALSE,
    options = list(
       pageLength = 25,
       lengthMenu = c(10, 25, 50, 100)
    )
  ) %>%
  formatPercentage(columns = 3, digits = 1)
```

