---
title: "Podcast Data for the Lulz"
output:
  html_document:
    toc: true
    code_folding: hide
---

```{r global_options, include=FALSE}
source("setup.R")
```

I'm migrating this from the old location to here, cleaning up the code and improving it when I can.  
The new repo is located [here](https://github.com/jemus42/podcaststats).  

This is still under heavy maintenance, and I'll replace this text when I consider it done(ish).

## Placeholder Quickie: Defocused vs. Reconcilable Differences

```{r}
defocused <- readRDS("data/incomparable_master_wide.rds") %>% 
                filter(podcast == "Defocused") %>%
                mutate(number = as.numeric(number))
recdiffs  <- readRDS("data/relay.rds") %>% 
                filter(podcast == "Reconcilable Differences")

data <- full_join(recdiffs, defocused)

ggplot(data = data, aes(x = podcast, y = duration, fill = podcast)) +
  geom_violin(draw_quantiles = c(.25, .75), alpha = .7) +
  stat_summary(fun.y = mean, geom = "point", size = 2) +
  coord_flip() +
  theme(legend.position = "top") +
  labs(title = "Defocused vs. Reconcilable Differences",
       subtitle = "Comparison of Show Durations (Violin Plot)", 
       x = "", y = "Duration (mins)", fill = "Show")
```

