name: Render & Deploy Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 0" # At 06:00 on Sunday.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: yes
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pins, any::paws.storage, local::.
      - name: Install system dependencies for renv-installed packages
        run: sudo apt install gsfonts libcairo2-dev libgit2-dev libmagick++-dev libx11-dev
      - uses: r-lib/actions/setup-renv@v2
      - uses: quarto-dev/quarto-actions/setup@v2


      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        run:

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
