name: Render & Deploy Site
on:
  push:
    branches: main
  schedule:
    - cron:  "0 6 * * 0" # At 06:00 on Sunday.

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-renv@v1

      - name: Install font
        run: brew install --cask font-public-sans

      - name: Get ATP data
        run: |
          library(poddr)
          atp <- atp_get_episodes()
          cache_podcast_data(atp, csv = FALSE)
        shell: Rscript {0}

      - name: Get Relay.fm data
        run: |
          library(poddr)
          relay_shows <- relay_get_shows()
          relay_episodes <- relay_get_episodes(relay_shows)
          cache_podcast_data(relay_shows)
          cache_podcast_data(relay_episodes)
        shell: Rscript {0}

      - name: Get The Incomparable data
        run: |
          library(poddr)
          incomparable_shows <- incomparable_get_shows()
          incomparable_episodes <- incomparable_get_episodes(incomparable_shows)
          cache_podcast_data(incomparable_shows)
          cache_podcast_data(incomparable_episodes)
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Copy data to public directory
        run: 'rm _site/data/.gitignore; cp data/* _site/data/'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: _site
