name: Render & Deploy Site
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 0" # At 06:00 on Sunday.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: yes
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pins, any::paws.storage, local::.
      - uses: r-lib/actions/setup-renv@v2
      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: keithweaver/aws-s3-github-action@v1
        name: Copy data from s3
        with:
          command: cp
          source: s3://jemsudatasets/podcaststats/
          destination: ./data/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          flags: --recursive

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
