on:
  push:
    branches: main

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-renv@v1

      - name: Install dependencies
        run: |
          renv::restore()
        shell: Rscript {0}

      - name: Get Data
        run: |
          library(poddr)

          atp <- atp_get_episodes()
          cache_podcast_data(atp, csv = FALSE)

          relay_shows <- relay_get_shows()
          relay_episodes <- relay_get_episodes(relay_shows)
          cache_podcast_data(relay_shows)
          cache_podcast_data(relay_episodes)

          incomparable_shows <- incomparable_get_shows()
          incomparable_episodes <- incomparable_get_episodes(incomparable_shows)

          cache_podcast_data(incomparable_shows)
          cache_podcast_data(incomparable_episodes)
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: _site
