name: Render & Deploy Site
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 0" # At 06:00 on Sunday.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: yes

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install Stuff
        run: |
          sudo apt install libcurl4-openssl-dev

      - uses: r-lib/actions/setup-renv@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: Copy data from s3
        with:
          command: cp
          source: s3://jemsudatasets/podcaststats/
          destination: ./data/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          flags: --recursive

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: _site
